/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDesktopRouteImport } from './routes/_authenticated.desktop'
import { Route as ApiPublicHooksScanHackathonsRouteImport } from './routes/api/public/hooks/scan-hackathons'
import { Route as ApiPublicHooksScanAiNewsRouteImport } from './routes/api/public/hooks/scan-ai-news'
import { Route as ApiPublicHooksDailyRecapRouteImport } from './routes/api/public/hooks/daily-recap'
import { Route as ApiPublicFeishuWebhookRouteImport } from './routes/api/public/feishu/webhook'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDesktopRoute = AuthenticatedDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksScanHackathonsRoute =
  ApiPublicHooksScanHackathonsRouteImport.update({
    id: '/api/public/hooks/scan-hackathons',
    path: '/api/public/hooks/scan-hackathons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanAiNewsRoute =
  ApiPublicHooksScanAiNewsRouteImport.update({
    id: '/api/public/hooks/scan-ai-news',
    path: '/api/public/hooks/scan-ai-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRecapRoute =
  ApiPublicHooksDailyRecapRouteImport.update({
    id: '/api/public/hooks/daily-recap',
    path: '/api/public/hooks/daily-recap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeishuWebhookRoute = ApiPublicFeishuWebhookRouteImport.update({
  id: '/api/public/feishu/webhook',
  path: '/api/public/feishu/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/desktop': typeof AuthenticatedDesktopRoute
  '/api/public/feishu/webhook': typeof ApiPublicFeishuWebhookRoute
  '/api/public/hooks/daily-recap': typeof ApiPublicHooksDailyRecapRoute
  '/api/public/hooks/scan-ai-news': typeof ApiPublicHooksScanAiNewsRoute
  '/api/public/hooks/scan-hackathons': typeof ApiPublicHooksScanHackathonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/desktop': typeof AuthenticatedDesktopRoute
  '/api/public/feishu/webhook': typeof ApiPublicFeishuWebhookRoute
  '/api/public/hooks/daily-recap': typeof ApiPublicHooksDailyRecapRoute
  '/api/public/hooks/scan-ai-news': typeof ApiPublicHooksScanAiNewsRoute
  '/api/public/hooks/scan-hackathons': typeof ApiPublicHooksScanHackathonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/desktop': typeof AuthenticatedDesktopRoute
  '/api/public/feishu/webhook': typeof ApiPublicFeishuWebhookRoute
  '/api/public/hooks/daily-recap': typeof ApiPublicHooksDailyRecapRoute
  '/api/public/hooks/scan-ai-news': typeof ApiPublicHooksScanAiNewsRoute
  '/api/public/hooks/scan-hackathons': typeof ApiPublicHooksScanHackathonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/desktop'
    | '/api/public/feishu/webhook'
    | '/api/public/hooks/daily-recap'
    | '/api/public/hooks/scan-ai-news'
    | '/api/public/hooks/scan-hackathons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/desktop'
    | '/api/public/feishu/webhook'
    | '/api/public/hooks/daily-recap'
    | '/api/public/hooks/scan-ai-news'
    | '/api/public/hooks/scan-hackathons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/desktop'
    | '/api/public/feishu/webhook'
    | '/api/public/hooks/daily-recap'
    | '/api/public/hooks/scan-ai-news'
    | '/api/public/hooks/scan-hackathons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicFeishuWebhookRoute: typeof ApiPublicFeishuWebhookRoute
  ApiPublicHooksDailyRecapRoute: typeof ApiPublicHooksDailyRecapRoute
  ApiPublicHooksScanAiNewsRoute: typeof ApiPublicHooksScanAiNewsRoute
  ApiPublicHooksScanHackathonsRoute: typeof ApiPublicHooksScanHackathonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/desktop': {
      id: '/_authenticated/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof AuthenticatedDesktopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/scan-hackathons': {
      id: '/api/public/hooks/scan-hackathons'
      path: '/api/public/hooks/scan-hackathons'
      fullPath: '/api/public/hooks/scan-hackathons'
      preLoaderRoute: typeof ApiPublicHooksScanHackathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-ai-news': {
      id: '/api/public/hooks/scan-ai-news'
      path: '/api/public/hooks/scan-ai-news'
      fullPath: '/api/public/hooks/scan-ai-news'
      preLoaderRoute: typeof ApiPublicHooksScanAiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-recap': {
      id: '/api/public/hooks/daily-recap'
      path: '/api/public/hooks/daily-recap'
      fullPath: '/api/public/hooks/daily-recap'
      preLoaderRoute: typeof ApiPublicHooksDailyRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feishu/webhook': {
      id: '/api/public/feishu/webhook'
      path: '/api/public/feishu/webhook'
      fullPath: '/api/public/feishu/webhook'
      preLoaderRoute: typeof ApiPublicFeishuWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDesktopRoute: typeof AuthenticatedDesktopRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDesktopRoute: AuthenticatedDesktopRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicFeishuWebhookRoute: ApiPublicFeishuWebhookRoute,
  ApiPublicHooksDailyRecapRoute: ApiPublicHooksDailyRecapRoute,
  ApiPublicHooksScanAiNewsRoute: ApiPublicHooksScanAiNewsRoute,
  ApiPublicHooksScanHackathonsRoute: ApiPublicHooksScanHackathonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
