/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedDesktopRouteImport } from './routes/_authenticated.desktop'
import { Route as AuthenticatedWidgetRouteImport } from './routes/_authenticated.widget'
import { Route as ApiLifeAgentRouteImport } from './routes/api/life-agent'
import { Route as ApiPublicCalendarTokenDoticsRouteImport } from './routes/api/public/calendar/$token[.]ics'
import { Route as ApiPublicFeishuWebhookRouteImport } from './routes/api/public/feishu/webhook'
import { Route as ApiPublicHooksDailyRecapRouteImport } from './routes/api/public/hooks/daily-recap'
import { Route as ApiPublicHooksGenerateInsightsRouteImport } from './routes/api/public/hooks/generate-insights'
import { Route as ApiPublicHooksScanAiNewsRouteImport } from './routes/api/public/hooks/scan-ai-news'
import { Route as ApiPublicHooksScanHackathonsRouteImport } from './routes/api/public/hooks/scan-hackathons'
import { Route as ApiPublicFeishuOauthCallbackRouteImport } from './routes/api/public/feishu/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesktopRoute = AuthenticatedDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWidgetRoute = AuthenticatedWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiLifeAgentRoute = ApiLifeAgentRouteImport.update({
  id: '/api/life-agent',
  path: '/api/life-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarTokenDoticsRoute =
  ApiPublicCalendarTokenDoticsRouteImport.update({
    id: '/api/public/calendar/$token.ics',
    path: '/api/public/calendar/$token.ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeishuWebhookRoute = ApiPublicFeishuWebhookRouteImport.update({
  id: '/api/public/feishu/webhook',
  path: '/api/public/feishu/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyRecapRoute =
  ApiPublicHooksDailyRecapRouteImport.update({
    id: '/api/public/hooks/daily-recap',
    path: '/api/public/hooks/daily-recap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateInsightsRoute =
  ApiPublicHooksGenerateInsightsRouteImport.update({
    id: '/api/public/hooks/generate-insights',
    path: '/api/public/hooks/generate-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanAiNewsRoute =
  ApiPublicHooksScanAiNewsRouteImport.update({
    id: '/api/public/hooks/scan-ai-news',
    path: '/api/public/hooks/scan-ai-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanHackathonsRoute =
  ApiPublicHooksScanHackathonsRouteImport.update({
    id: '/api/public/hooks/scan-hackathons',
    path: '/api/public/hooks/scan-hackathons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeishuOauthCallbackRoute =
  ApiPublicFeishuOauthCallbackRouteImport.update({
    id: '/api/public/feishu/oauth/callback',
    path: '/api/public/feishu/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/desktop': typeof AuthenticatedDesktopRoute
  '/widget': typeof AuthenticatedWidgetRoute
  '/api/life-agent': typeof ApiLifeAgentRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
  '/api/public/feishu/webhook': typeof ApiPublicFeishuWebhookRoute
  '/api/public/hooks/daily-recap': typeof ApiPublicHooksDailyRecapRoute
  '/api/public/hooks/generate-insights': typeof ApiPublicHooksGenerateInsightsRoute
  '/api/public/hooks/scan-ai-news': typeof ApiPublicHooksScanAiNewsRoute
  '/api/public/hooks/scan-hackathons': typeof ApiPublicHooksScanHackathonsRoute
  '/api/public/feishu/oauth/callback': typeof ApiPublicFeishuOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/desktop': typeof AuthenticatedDesktopRoute
  '/widget': typeof AuthenticatedWidgetRoute
  '/api/life-agent': typeof ApiLifeAgentRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
  '/api/public/feishu/webhook': typeof ApiPublicFeishuWebhookRoute
  '/api/public/hooks/daily-recap': typeof ApiPublicHooksDailyRecapRoute
  '/api/public/hooks/generate-insights': typeof ApiPublicHooksGenerateInsightsRoute
  '/api/public/hooks/scan-ai-news': typeof ApiPublicHooksScanAiNewsRoute
  '/api/public/hooks/scan-hackathons': typeof ApiPublicHooksScanHackathonsRoute
  '/api/public/feishu/oauth/callback': typeof ApiPublicFeishuOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/desktop': typeof AuthenticatedDesktopRoute
  '/_authenticated/widget': typeof AuthenticatedWidgetRoute
  '/api/life-agent': typeof ApiLifeAgentRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
  '/api/public/feishu/webhook': typeof ApiPublicFeishuWebhookRoute
  '/api/public/hooks/daily-recap': typeof ApiPublicHooksDailyRecapRoute
  '/api/public/hooks/generate-insights': typeof ApiPublicHooksGenerateInsightsRoute
  '/api/public/hooks/scan-ai-news': typeof ApiPublicHooksScanAiNewsRoute
  '/api/public/hooks/scan-hackathons': typeof ApiPublicHooksScanHackathonsRoute
  '/api/public/feishu/oauth/callback': typeof ApiPublicFeishuOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/login'
    | '/admin'
    | '/calendar'
    | '/desktop'
    | '/widget'
    | '/api/life-agent'
    | '/api/public/calendar/$token.ics'
    | '/api/public/feishu/webhook'
    | '/api/public/hooks/daily-recap'
    | '/api/public/hooks/generate-insights'
    | '/api/public/hooks/scan-ai-news'
    | '/api/public/hooks/scan-hackathons'
    | '/api/public/feishu/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/login'
    | '/admin'
    | '/calendar'
    | '/desktop'
    | '/widget'
    | '/api/life-agent'
    | '/api/public/calendar/$token.ics'
    | '/api/public/feishu/webhook'
    | '/api/public/hooks/daily-recap'
    | '/api/public/hooks/generate-insights'
    | '/api/public/hooks/scan-ai-news'
    | '/api/public/hooks/scan-hackathons'
    | '/api/public/feishu/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/download'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/desktop'
    | '/_authenticated/widget'
    | '/api/life-agent'
    | '/api/public/calendar/$token.ics'
    | '/api/public/feishu/webhook'
    | '/api/public/hooks/daily-recap'
    | '/api/public/hooks/generate-insights'
    | '/api/public/hooks/scan-ai-news'
    | '/api/public/hooks/scan-hackathons'
    | '/api/public/feishu/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  ApiLifeAgentRoute: typeof ApiLifeAgentRoute
  ApiPublicCalendarTokenDoticsRoute: typeof ApiPublicCalendarTokenDoticsRoute
  ApiPublicFeishuWebhookRoute: typeof ApiPublicFeishuWebhookRoute
  ApiPublicHooksDailyRecapRoute: typeof ApiPublicHooksDailyRecapRoute
  ApiPublicHooksGenerateInsightsRoute: typeof ApiPublicHooksGenerateInsightsRoute
  ApiPublicHooksScanAiNewsRoute: typeof ApiPublicHooksScanAiNewsRoute
  ApiPublicHooksScanHackathonsRoute: typeof ApiPublicHooksScanHackathonsRoute
  ApiPublicFeishuOauthCallbackRoute: typeof ApiPublicFeishuOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/desktop': {
      id: '/_authenticated/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof AuthenticatedDesktopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/widget': {
      id: '/_authenticated/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof AuthenticatedWidgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/life-agent': {
      id: '/api/life-agent'
      path: '/api/life-agent'
      fullPath: '/api/life-agent'
      preLoaderRoute: typeof ApiLifeAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token.ics': {
      id: '/api/public/calendar/$token.ics'
      path: '/api/public/calendar/$token.ics'
      fullPath: '/api/public/calendar/$token.ics'
      preLoaderRoute: typeof ApiPublicCalendarTokenDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feishu/webhook': {
      id: '/api/public/feishu/webhook'
      path: '/api/public/feishu/webhook'
      fullPath: '/api/public/feishu/webhook'
      preLoaderRoute: typeof ApiPublicFeishuWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-recap': {
      id: '/api/public/hooks/daily-recap'
      path: '/api/public/hooks/daily-recap'
      fullPath: '/api/public/hooks/daily-recap'
      preLoaderRoute: typeof ApiPublicHooksDailyRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-insights': {
      id: '/api/public/hooks/generate-insights'
      path: '/api/public/hooks/generate-insights'
      fullPath: '/api/public/hooks/generate-insights'
      preLoaderRoute: typeof ApiPublicHooksGenerateInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-ai-news': {
      id: '/api/public/hooks/scan-ai-news'
      path: '/api/public/hooks/scan-ai-news'
      fullPath: '/api/public/hooks/scan-ai-news'
      preLoaderRoute: typeof ApiPublicHooksScanAiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-hackathons': {
      id: '/api/public/hooks/scan-hackathons'
      path: '/api/public/hooks/scan-hackathons'
      fullPath: '/api/public/hooks/scan-hackathons'
      preLoaderRoute: typeof ApiPublicHooksScanHackathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feishu/oauth/callback': {
      id: '/api/public/feishu/oauth/callback'
      path: '/api/public/feishu/oauth/callback'
      fullPath: '/api/public/feishu/oauth/callback'
      preLoaderRoute: typeof ApiPublicFeishuOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDesktopRoute: typeof AuthenticatedDesktopRoute
  AuthenticatedWidgetRoute: typeof AuthenticatedWidgetRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDesktopRoute: AuthenticatedDesktopRoute,
  AuthenticatedWidgetRoute: AuthenticatedWidgetRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  ApiLifeAgentRoute: ApiLifeAgentRoute,
  ApiPublicCalendarTokenDoticsRoute: ApiPublicCalendarTokenDoticsRoute,
  ApiPublicFeishuWebhookRoute: ApiPublicFeishuWebhookRoute,
  ApiPublicHooksDailyRecapRoute: ApiPublicHooksDailyRecapRoute,
  ApiPublicHooksGenerateInsightsRoute: ApiPublicHooksGenerateInsightsRoute,
  ApiPublicHooksScanAiNewsRoute: ApiPublicHooksScanAiNewsRoute,
  ApiPublicHooksScanHackathonsRoute: ApiPublicHooksScanHackathonsRoute,
  ApiPublicFeishuOauthCallbackRoute: ApiPublicFeishuOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
